In [1]:
import pandas as pd
import numpy as np

# ETLS

En este notbook se proporcionarán los pasos realizados para la limpieza y analisis de los datasets con los que vamos a partir para el desarrollo del proyecto. El fin es conseguir un dataset limpio y sencillo con el que poder jugar y así poder desarrollar nuestra idea de proyecto.

## Centros médicos Madrid

In [2]:
centros_medicos = pd.read_csv("../data/centros_medicos_madrid.csv", encoding='latin-1', sep=';', error_bad_lines=False)
centros_medicos.head()

,PK,NOMBRE,DESCRIPCION-ENTIDAD,HORARIO,EQUIPAMIENTO,TRANSPORTE,DESCRIPCION,ACCESIBILIDAD,CONTENT-URL,NOMBRE-VIA,...,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,FAX,EMAIL,TIPO,Unnamed: 30
0,134929,Centro Concertado de Atención a las Adicciones...,El CCAD Cáritas que forma parte de la red del ...,"De lunes a viernes mañanas de 9 a 14 horas, ta...",Valoración interdisciplinar del/de la paciente...,"Bus: 9, 73, N2Metro: Alfonso XIII (L4), Prospe...",NaN,1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,SANTA HORTENSIA,...,CHAMARTIN,443159,4477482,40.446.053.313.442.700,-36.702.766.124.516.500,917 440 599,NaN,tto.adicciones@caritasmadrid.org,/contenido/entidadesYorganismos/CentrosAtencio...,
1,53123,Centro Concertado de Atención a las Adicciones...,El CCAD Casa de Campo que forma parte de la r...,De lunes a viernes de 9 a 17 horas,Valoración interdisciplinar del paciente.Trata...,"Bus: 31, 33, 36, 39, 65, 138Metro:Puerta del A...",Forma de acceso: directo,1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,PORTUGAL,...,LATINA,438577,4474219,4.041.633.059.885.880,-37.239.914.257.003.300,914 799 499,NaN,NaN,/contenido/entidadesYorganismos/CentrosAtencio...,
2,11867,Centro de Atención a las Adicciones (CAD) de A...,NaN,Horario ordinario:De lunes a jueves de 8 a 20:...,Valoración por equipo interdisciplinarTratamie...,"Bus: 6 , 8 , 18 , 19 , 22 , 45 , 47 , 76 , 78 ...","Forma de acceso: directo, a través de los serv...",1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,CHOPERA,...,ARGANZUELA,440757,4471619,4.039.305.745.803.060,-36.980.673.403.694.100,915 886 186 \n915 886 189,NaN,cadarganzuela@madrid.es,/contenido/entidadesYorganismos/CentrosAtencio...,
3,11887,Centro de Atención a las Adicciones (CAD) de H...,NaN,Horario ordinario:De lunes a jueves de 8 a 20:...,Valoración por equipo interdisciplinarTratamie...,"Bus: 73, 87, 104, 112, 120, 125, 153, 172Metro...","Acceso: directo, a través de los servicios mun...",1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,MINAYA,...,HORTALEZA,446072,4479929,40.468.288.815.918.500,-3.636.150.078.507.100,913 822 530,NaN,cadhortaleza@madrid. es,/contenido/entidadesYorganismos/CentrosAtencio...,
4,11862,Centro de Atención a las Adicciones (CAD) de L...,NaN,Horario ordinario:De lunes a jueves de 8 a 20:...,Valoración por equipo interdisciplinarTratamie...,"Bus: 25 , 31, 138Metro: Laguna (L 6), Casa de ...","Acceso: directo, a traves de los servicios mun...",1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,CAMARENA,...,LATINA,435820,4471982,4.039.597.072.367.930,-37.562.716.852.987.800,917 198 989,NaN,cadlatina@madrid.es,/contenido/entidadesYorganismos/CentrosAtencio...,

In [3]:
centros_medicos.shape

(270, 31)

In [4]:
centros_medicos.keys()

Index(['PK', 'NOMBRE', 'DESCRIPCION-ENTIDAD', 'HORARIO', 'EQUIPAMIENTO',
       'TRANSPORTE', 'DESCRIPCION', 'ACCESIBILIDAD', 'CONTENT-URL',
       'NOMBRE-VIA', 'CLASE-VIAL', 'TIPO-NUM', 'NUM', 'PLANTA', 'PUERTA',
       'ESCALERAS', 'ORIENTACION', 'LOCALIDAD', 'PROVINCIA', 'CODIGO-POSTAL',
       'BARRIO', 'DISTRITO', 'COORDENADA-X', 'COORDENADA-Y', 'LATITUD',
       'LONGITUD', 'TELEFONO', 'FAX', 'EMAIL', 'TIPO', 'Unnamed: 30'],
      dtype='object')

In [5]:
centros_medicos.isnull().sum()

PK                       0
NOMBRE                   0
DESCRIPCION-ENTIDAD    258
HORARIO                 65
EQUIPAMIENTO            87
TRANSPORTE               1
DESCRIPCION            214
ACCESIBILIDAD            0
CONTENT-URL              0
NOMBRE-VIA               0
CLASE-VIAL               0
TIPO-NUM                 0
NUM                      4
PLANTA                 256
PUERTA                 268
ESCALERAS              270
ORIENTACION            250
LOCALIDAD                0
PROVINCIA                0
CODIGO-POSTAL            1
BARRIO                   5
DISTRITO                 0
COORDENADA-X             0
COORDENADA-Y             0
LATITUD                  0
LONGITUD                 0
TELEFONO                 0
FAX                    228
EMAIL                  216
TIPO                     0
Unnamed: 30              0
dtype: int64

* Como vemos hay muchas columnas que tienen mucshísimos valores nulos y las vamos a tener que eliminar
* La eliminación de estas columnas no influye en absoluto con el desarrollo de nuestro proyecto porque esa información no es relevante para conseguir el fin de este trabajo
* Por lo tanto eliminaremos las siguientes diez columnas: 
    - DESCRIPCION-ENTIDAD
    - HORARIO
    - EQUIPAMIENTO
    - DESCRIPCION
    - PLANTA
    - PUERTA
    - ESCALERAS
    - ORIENTACION
    - FAX
    - EMAIL

In [6]:
centros_medicos = centros_medicos.drop(['DESCRIPCION-ENTIDAD', 'HORARIO', 'EQUIPAMIENTO', 'DESCRIPCION', 'PLANTA', 'PUERTA', 'ESCALERAS', 'ORIENTACION', 'FAX', 'EMAIL'], axis=1)
centros_medicos.head()

,PK,NOMBRE,TRANSPORTE,ACCESIBILIDAD,CONTENT-URL,NOMBRE-VIA,CLASE-VIAL,TIPO-NUM,NUM,LOCALIDAD,...,CODIGO-POSTAL,BARRIO,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TELEFONO,TIPO,Unnamed: 30
0,134929,Centro Concertado de Atención a las Adicciones...,"Bus: 9, 73, N2Metro: Alfonso XIII (L4), Prospe...",1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,SANTA HORTENSIA,CALLE,V,1.0,MADRID,...,28002.0,PROSPERIDAD,CHAMARTIN,443159,4477482,40.446.053.313.442.700,-36.702.766.124.516.500,917 440 599,/contenido/entidadesYorganismos/CentrosAtencio...,
1,53123,Centro Concertado de Atención a las Adicciones...,"Bus: 31, 33, 36, 39, 65, 138Metro:Puerta del A...",1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,PORTUGAL,AVENIDA,V,0.0,MADRID,...,28011.0,PUERTA DEL ANGEL,LATINA,438577,4474219,4.041.633.059.885.880,-37.239.914.257.003.300,914 799 499,/contenido/entidadesYorganismos/CentrosAtencio...,
2,11867,Centro de Atención a las Adicciones (CAD) de A...,"Bus: 6 , 8 , 18 , 19 , 22 , 45 , 47 , 76 , 78 ...",1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,CHOPERA,PASEO,V,12.0,MADRID,...,28045.0,CHOPERA,ARGANZUELA,440757,4471619,4.039.305.745.803.060,-36.980.673.403.694.100,915 886 186 \n915 886 189,/contenido/entidadesYorganismos/CentrosAtencio...,
3,11887,Centro de Atención a las Adicciones (CAD) de H...,"Bus: 73, 87, 104, 112, 120, 125, 153, 172Metro...",1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,MINAYA,CALLE,V,7.0,MADRID,...,28043.0,CANILLAS,HORTALEZA,446072,4479929,40.468.288.815.918.500,-3.636.150.078.507.100,913 822 530,/contenido/entidadesYorganismos/CentrosAtencio...,
4,11862,Centro de Atención a las Adicciones (CAD) de L...,"Bus: 25 , 31, 138Metro: Laguna (L 6), Casa de ...",1,http://www.madrid.es/sites/v/index.jsp?vgnextc...,CAMARENA,CALLE,V,10.0,MADRID,...,28047.0,ALUCHE,LATINA,435820,4471982,4.039.597.072.367.930,-37.562.716.852.987.800,917 198 989,/contenido/entidadesYorganismos/CentrosAtencio...,

In [7]:
centros_medicos.isnull().sum()

PK               0
NOMBRE           0
TRANSPORTE       1
ACCESIBILIDAD    0
CONTENT-URL      0
NOMBRE-VIA       0
CLASE-VIAL       0
TIPO-NUM         0
NUM              4
LOCALIDAD        0
PROVINCIA        0
CODIGO-POSTAL    1
BARRIO           5
DISTRITO         0
COORDENADA-X     0
COORDENADA-Y     0
LATITUD          0
LONGITUD         0
TELEFONO         0
TIPO             0
Unnamed: 30      0
dtype: int64

In [9]:
centros_medicos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PK             270 non-null    int64
 1   NOMBRE         270 non-null    object
 2   TRANSPORTE     269 non-null    object
 3   ACCESIBILIDAD  270 non-null    int64
 4   CONTENT-URL    270 non-null    object
 5   NOMBRE-VIA     270 non-null    object
 6   CLASE-VIAL     270 non-null    object
 7   TIPO-NUM       270 non-null    object
 8   NUM            266 non-null    float64
 9   LOCALIDAD      270 non-null    object
 10  PROVINCIA      270 non-null    object
 11  CODIGO-POSTAL  269 non-null    float64
 12  BARRIO         265 non-null    object
 13  DISTRITO       270 non-null    object
 14  COORDENADA-X   270 non-null    int64
 15  COORDENADA-Y   270 non-null    int64
 16  LATITUD        270 non-null    object
 17  LONGITUD       270 non-null    object
 18  TELEFONO       270 non-null    object
 19  TIPO           270 non-null    object
 20  Unnamed: 30    270 non-null    object
dtypes: float64(2), int64(4), object(15)
memory usage: 44.4+ KB

### Estudio profundo de los datos de cada columna

In [10]:
# Concatenar con tipo de via y nº para obtenter la dirección completa en solamente una columna
centros_medicos['NOMBRE-VIA']

0      SANTA HORTENSIA
1             PORTUGAL
2              CHOPERA
3               MINAYA
4             CAMARENA
            ...
265     CANDIDO MATEOS
266          AGUILEÑAS
267                REY
268            MONTESA
269       ARTURO SORIA
Name: NOMBRE-VIA, Length: 270, dtype: object

In [11]:
# Concatenar con nombre de la vía via y nº para obtenter la dirección completa en solamente una columna
centros_medicos['CLASE-VIAL']

0        CALLE
1      AVENIDA
2        PASEO
3        CALLE
4        CALLE
        ...
265      CALLE
266      CALLE
267      PASEO
268      CALLE
269      CALLE
Name: CLASE-VIAL, Length: 270, dtype: object

In [12]:
# Vamos a eliminar esta columna, información irrelevante para nuestro proyecto 
centros_medicos['TIPO-NUM'].unique()

array(['V', 'NUM', 'T'], dtype=object)

In [13]:
# Concatenar con tipo de via y nombre de la vía para obtenter la dirección completa en solamente una columna
centros_medicos['NUM']

0        1.0
1        0.0
2       12.0
3        7.0
4       10.0
       ...
265     11.0
266      1.0
267      NaN
268     22.0
269    103.0
Name: NUM, Length: 270, dtype: float64

In [14]:
# Podemos eliminar esta columna ya que TODAS SON de madrid
centros_medicos['LOCALIDAD'].unique()

array(['MADRID'], dtype=object)

In [15]:
# Podemos eliminarla ya que TODAS SON de madrid
centros_medicos['PROVINCIA'].unique()

array(['MADRID'], dtype=object)

In [16]:
# QUITAR LOS CEROS
centros_medicos['CODIGO-POSTAL']

0      28002.0
1      28011.0
2      28045.0
3      28043.0
4      28047.0
        ...
265    28035.0
266    28029.0
267    28008.0
268    28006.0
269    28043.0
Name: CODIGO-POSTAL, Length: 270, dtype: float64

In [17]:
# Vamos a eliminar esta columna, nos vamos a quedr solmente con el distrito
centros_medicos['BARRIO']

0            PROSPERIDAD
1       PUERTA DEL ANGEL
2                CHOPERA
3               CANILLAS
4                 ALUCHE
             ...
265          PEÑA GRANDE
266             ALMENARA
267            ARGUELLES
268                LISTA
269    SAN JUAN BAUTISTA
Name: BARRIO, Length: 270, dtype: object

In [18]:
centros_medicos['DISTRITO']

0                CHAMARTIN
1                   LATINA
2               ARGANZUELA
3                HORTALEZA
4                   LATINA
              ...
265    FUENCARRAL-EL PARDO
266                 TETUAN
267        MONCLOA-ARAVACA
268              SALAMANCA
269          CIUDAD LINEAL
Name: DISTRITO, Length: 270, dtype: object

In [19]:
centros_medicos.TIPO[0]

'/contenido/entidadesYorganismos/CentrosAtencionMedica/CentrosAsistenciaDrogodependientes'

### Eliminación de las columnas con datos irrelevantes para el desarrollo de este proyecto

In [20]:
centros_medicos = centros_medicos.drop(['PK', 'TRANSPORTE', 'ACCESIBILIDAD', 'CONTENT-URL', 'TIPO-NUM', 'LOCALIDAD', 'PROVINCIA', 'BARRIO', 'TELEFONO'], axis=1)
centros_medicos.head()

,NOMBRE,NOMBRE-VIA,CLASE-VIAL,NUM,CODIGO-POSTAL,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TIPO,Unnamed: 30
0,Centro Concertado de Atención a las Adicciones...,SANTA HORTENSIA,CALLE,1.0,28002.0,CHAMARTIN,443159,4477482,40.446.053.313.442.700,-36.702.766.124.516.500,/contenido/entidadesYorganismos/CentrosAtencio...,
1,Centro Concertado de Atención a las Adicciones...,PORTUGAL,AVENIDA,0.0,28011.0,LATINA,438577,4474219,4.041.633.059.885.880,-37.239.914.257.003.300,/contenido/entidadesYorganismos/CentrosAtencio...,
2,Centro de Atención a las Adicciones (CAD) de A...,CHOPERA,PASEO,12.0,28045.0,ARGANZUELA,440757,4471619,4.039.305.745.803.060,-36.980.673.403.694.100,/contenido/entidadesYorganismos/CentrosAtencio...,
3,Centro de Atención a las Adicciones (CAD) de H...,MINAYA,CALLE,7.0,28043.0,HORTALEZA,446072,4479929,40.468.288.815.918.500,-3.636.150.078.507.100,/contenido/entidadesYorganismos/CentrosAtencio...,
4,Centro de Atención a las Adicciones (CAD) de L...,CAMARENA,CALLE,10.0,28047.0,LATINA,435820,4471982,4.039.597.072.367.930,-37.562.716.852.987.800,/contenido/entidadesYorganismos/CentrosAtencio...,

In [21]:
centros_medicos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   NOMBRE         270 non-null    object
 1   NOMBRE-VIA     270 non-null    object
 2   CLASE-VIAL     270 non-null    object
 3   NUM            266 non-null    float64
 4   CODIGO-POSTAL  269 non-null    float64
 5   DISTRITO       270 non-null    object
 6   COORDENADA-X   270 non-null    int64
 7   COORDENADA-Y   270 non-null    int64
 8   LATITUD        270 non-null    object
 9   LONGITUD       270 non-null    object
 10  TIPO           270 non-null    object
 11  Unnamed: 30    270 non-null    object
dtypes: float64(2), int64(2), object(8)
memory usage: 25.4+ KB

#### Concatenamos columnas.
Pasos a seguir: 
    
    1. Primero cambiaremos los valores nulos por un cero
    2. Tranformaremos la columa de float a string
    3. Concatenaremos las columnas: Clase de via, Nombre de via y nº de via
    3. La del codigo postal aún no la junto porque tengo una idea (me gustaria que en la API con tan solo poner el codigo postas en vez de la latitud y longitud funcionara y te devolviera los tiempos, la distancia y la ruta)

In [22]:
centros_medicos.isnull().sum()

NOMBRE           0
NOMBRE-VIA       0
CLASE-VIAL       0
NUM              4
CODIGO-POSTAL    1
DISTRITO         0
COORDENADA-X     0
COORDENADA-Y     0
LATITUD          0
LONGITUD         0
TIPO             0
Unnamed: 30      0
dtype: int64

In [23]:
centros_medicos['NUMERO'] = centros_medicos['NUM'].fillna(0).astype(np.int64)
centros_medicos['NUMERO'] = centros_medicos['NUMERO'].astype(str)

In [24]:
centros_medicos['COD_POSTAL'] = centros_medicos['CODIGO-POSTAL'].fillna(0).astype(np.int64)
centros_medicos['COD_POSTAL'] = centros_medicos['COD_POSTAL'].astype(str)

In [25]:
centros_medicos = centros_medicos.drop(['NUM', 'CODIGO-POSTAL', 'Unnamed: 30'], axis=1)
centros_medicos.head()

,NOMBRE,NOMBRE-VIA,CLASE-VIAL,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TIPO,NUMERO,COD_POSTAL
0,Centro Concertado de Atención a las Adicciones...,SANTA HORTENSIA,CALLE,CHAMARTIN,443159,4477482,40.446.053.313.442.700,-36.702.766.124.516.500,/contenido/entidadesYorganismos/CentrosAtencio...,1,28002
1,Centro Concertado de Atención a las Adicciones...,PORTUGAL,AVENIDA,LATINA,438577,4474219,4.041.633.059.885.880,-37.239.914.257.003.300,/contenido/entidadesYorganismos/CentrosAtencio...,0,28011
2,Centro de Atención a las Adicciones (CAD) de A...,CHOPERA,PASEO,ARGANZUELA,440757,4471619,4.039.305.745.803.060,-36.980.673.403.694.100,/contenido/entidadesYorganismos/CentrosAtencio...,12,28045
3,Centro de Atención a las Adicciones (CAD) de H...,MINAYA,CALLE,HORTALEZA,446072,4479929,40.468.288.815.918.500,-3.636.150.078.507.100,/contenido/entidadesYorganismos/CentrosAtencio...,7,28043
4,Centro de Atención a las Adicciones (CAD) de L...,CAMARENA,CALLE,LATINA,435820,4471982,4.039.597.072.367.930,-37.562.716.852.987.800,/contenido/entidadesYorganismos/CentrosAtencio...,10,28047

In [26]:
centros_medicos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   NOMBRE        270 non-null    object
 1   NOMBRE-VIA    270 non-null    object
 2   CLASE-VIAL    270 non-null    object
 3   DISTRITO      270 non-null    object
 4   COORDENADA-X  270 non-null    int64
 5   COORDENADA-Y  270 non-null    int64
 6   LATITUD       270 non-null    object
 7   LONGITUD      270 non-null    object
 8   TIPO          270 non-null    object
 9   NUMERO        270 non-null    object
 10  COD_POSTAL    270 non-null    object
dtypes: int64(2), object(9)
memory usage: 23.3+ KB

In [27]:
centros_medicos['DIRECCION'] = centros_medicos['CLASE-VIAL'] + ' ' + centros_medicos['NOMBRE-VIA'] + ' ' + centros_medicos['NUMERO']

In [28]:
centros_medicos = centros_medicos.drop(['NOMBRE-VIA', 'CLASE-VIAL', 'NUMERO'], axis=1)
centros_medicos.head()

,NOMBRE,DISTRITO,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TIPO,COD_POSTAL,DIRECCION
0,Centro Concertado de Atención a las Adicciones...,CHAMARTIN,443159,4477482,40.446.053.313.442.700,-36.702.766.124.516.500,/contenido/entidadesYorganismos/CentrosAtencio...,28002,CALLE SANTA HORTENSIA 1
1,Centro Concertado de Atención a las Adicciones...,LATINA,438577,4474219,4.041.633.059.885.880,-37.239.914.257.003.300,/contenido/entidadesYorganismos/CentrosAtencio...,28011,AVENIDA PORTUGAL 0
2,Centro de Atención a las Adicciones (CAD) de A...,ARGANZUELA,440757,4471619,4.039.305.745.803.060,-36.980.673.403.694.100,/contenido/entidadesYorganismos/CentrosAtencio...,28045,PASEO CHOPERA 12
3,Centro de Atención a las Adicciones (CAD) de H...,HORTALEZA,446072,4479929,40.468.288.815.918.500,-3.636.150.078.507.100,/contenido/entidadesYorganismos/CentrosAtencio...,28043,CALLE MINAYA 7
4,Centro de Atención a las Adicciones (CAD) de L...,LATINA,435820,4471982,4.039.597.072.367.930,-37.562.716.852.987.800,/contenido/entidadesYorganismos/CentrosAtencio...,28047,CALLE CAMARENA 10

In [30]:
centros_medicos_clean = centros_medicos.reindex(columns=['NOMBRE','DIRECCION','DISTRITO','COD_POSTAL','COORDENADA-X', 'COORDENADA-Y', 'LATITUD', 'LONGITUD', 'TIPO'])
centros_medicos_clean.head()

,NOMBRE,DIRECCION,DISTRITO,COD_POSTAL,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TIPO
0,Centro Concertado de Atención a las Adicciones...,CALLE SANTA HORTENSIA 1,CHAMARTIN,28002,443159,4477482,40.446.053.313.442.700,-36.702.766.124.516.500,/contenido/entidadesYorganismos/CentrosAtencio...
1,Centro Concertado de Atención a las Adicciones...,AVENIDA PORTUGAL 0,LATINA,28011,438577,4474219,4.041.633.059.885.880,-37.239.914.257.003.300,/contenido/entidadesYorganismos/CentrosAtencio...
2,Centro de Atención a las Adicciones (CAD) de A...,PASEO CHOPERA 12,ARGANZUELA,28045,440757,4471619,4.039.305.745.803.060,-36.980.673.403.694.100,/contenido/entidadesYorganismos/CentrosAtencio...
3,Centro de Atención a las Adicciones (CAD) de H...,CALLE MINAYA 7,HORTALEZA,28043,446072,4479929,40.468.288.815.918.500,-3.636.150.078.507.100,/contenido/entidadesYorganismos/CentrosAtencio...
4,Centro de Atención a las Adicciones (CAD) de L...,CALLE CAMARENA 10,LATINA,28047,435820,4471982,4.039.597.072.367.930,-37.562.716.852.987.800,/contenido/entidadesYorganismos/CentrosAtencio...

###  LATITUD Y LONGITUD
Como podemos observar la latitud y longitud tiene una sintaxis NO válida para a posteriori plotear mapas y calcular distancias por lo que ahora necesitamos:

1. Eliminar todos los caratares(puntos) que haya entre medias de los numero que forman la longitud y latitud

2. Y luego, añadirle un punto entre la segunda posicion y tercera posicion de cada elemeno de la columna de Longitud y Latitud
  
   * ¡OJO! En la losngitud el simbolo menos (-) es necesario y cuenta como una posicion
   
   
3. Convertiremos estas dos columas a intengers para tener acabada nuestro análisis y limpieza de nuestro csv de centros medicos en madrid

A) LATITUD

In [31]:
centros_medicos_clean['LATITUD'] = centros_medicos_clean['LATITUD'].str.replace('.', '')

In [32]:
centros_medicos_clean['LATITUD'] = centros_medicos_clean['LATITUD'].apply(lambda x: x[:2] + '.' + x[2:])
centros_medicos_clean['LATITUD']

0      40.446053313442700
1       40.41633059885880
2       40.39305745803060
3      40.468288815918500
4       40.39597072367930
              ...
265     40.47277245807720
266     40.46548064796590
267     40.42054836583690
268    40.428976927386800
269    40.449787026276600
Name: LATITUD, Length: 270, dtype: object

B) LONGITUD

In [33]:
centros_medicos_clean['LONGITUD'] = centros_medicos_clean['LONGITUD'].str.replace('.', '')

In [34]:
centros_medicos_clean['LONGITUD'] = centros_medicos_clean['LONGITUD'].apply(lambda x: x[:2] + '.' + x[2:])
centros_medicos_clean['LONGITUD']

0      -3.6702766124516500
1      -3.7239914257003300
2      -3.6980673403694100
3       -3.636150078507100
4      -3.7562716852987800
              ...
265      -3.71813267268184
266    -3.6936383781020600
267    -3.7179660205926200
268    -3.6721607026353800
269     -3.651729403937950
Name: LONGITUD, Length: 270, dtype: object

###  TIPO
Los tipos de centros medicos si nos damos cuenta son nombres muy largos, por lo que vamos a inspeccionar un poco sobre ellos y ver si podemos acortarlos de alguna manera para poder diferenciarlos mejor.

In [35]:
centros_medicos_clean['TIPO']

0      /contenido/entidadesYorganismos/CentrosAtencio...
1      /contenido/entidadesYorganismos/CentrosAtencio...
2      /contenido/entidadesYorganismos/CentrosAtencio...
3      /contenido/entidadesYorganismos/CentrosAtencio...
4      /contenido/entidadesYorganismos/CentrosAtencio...
                             ...
265    /contenido/entidadesYorganismos/CentrosAtencio...
266    /contenido/entidadesYorganismos/CentrosAtencio...
267    /contenido/entidadesYorganismos/CentrosAtencio...
268    /contenido/entidadesYorganismos/CentrosAtencio...
269    /contenido/entidadesYorganismos/CentrosAtencio...
Name: TIPO, Length: 270, dtype: object

In [36]:
centros_medicos_clean['TIPO'].unique()

array(['/contenido/entidadesYorganismos/CentrosAtencionMedica/CentrosAsistenciaDrogodependientes',
       '/contenido/entidadesYorganismos/CentrosAtencionMedica/OtrosCentrosMedicos',
       '/contenido/entidadesYorganismos/CentrosAtencionMedica/CentrosEspecialidadesMedicas',
       '/contenido/entidadesYorganismos/CentrosAtencionMedica/CentrosSalud',
       '/contenido/entidadesYorganismos/CentrosAtencionSocial/CentrosRehabilitacionPsicosocial',
       '/contenido/entidadesYorganismos/CentrosAtencionMedica/CentrosPrevencionEnfermedades',
       '/contenido/entidadesYorganismos/CentrosAtencionMedica/CentrosSaludMental',
       '/contenido/entidadesYorganismos/CentrosAtencionMedica/HospitalesClinicasSanatorios'],
      dtype=object)

* Voy a eliminar los primeros 54 caracteres porque en todos son los mismo y asi vamos a poder diferencias mucho mejor los tipos de centros medicos que hay en madrid.

In [37]:
centros_medicos_clean['TIPO'] = centros_medicos_clean['TIPO'].apply(lambda x: x[54:])
centros_medicos_clean['TIPO']

0      CentrosAsistenciaDrogodependientes
1      CentrosAsistenciaDrogodependientes
2      CentrosAsistenciaDrogodependientes
3      CentrosAsistenciaDrogodependientes
4      CentrosAsistenciaDrogodependientes
                      ...
265                    CentrosSaludMental
266                    CentrosSaludMental
267    CentrosAsistenciaDrogodependientes
268         CentrosPrevencionEnfermedades
269          HospitalesClinicasSanatorios
Name: TIPO, Length: 270, dtype: object

In [38]:
centros_medicos_clean['TIPO'].unique()

array(['CentrosAsistenciaDrogodependientes', 'OtrosCentrosMedicos',
       'CentrosEspecialidadesMedicas', 'CentrosSalud',
       'CentrosRehabilitacionPsicosocial',
       'CentrosPrevencionEnfermedades', 'CentrosSaludMental',
       'HospitalesClinicasSanatorios'], dtype=object)

In [65]:
# Comprobamos si se han cambiado las longitudes y latitudes a como estabamos buscando
centros_medicos_clean.head()

,NOMBRE,DIRECCION,DISTRITO,COD_POSTAL,COORDENADA-X,COORDENADA-Y,LATITUD,LONGITUD,TIPO
0,Centro Concertado de Atención a las Adicciones...,CALLE SANTA HORTENSIA 1,CHAMARTIN,28002,443159,4477482,40.446053313442700,-3.6702766124516500,CentrosAsistenciaDrogodependientes
1,Centro Concertado de Atención a las Adicciones...,AVENIDA PORTUGAL 0,LATINA,28011,438577,4474219,40.41633059885880,-3.7239914257003300,CentrosAsistenciaDrogodependientes
2,Centro de Atención a las Adicciones (CAD) de A...,PASEO CHOPERA 12,ARGANZUELA,28045,440757,4471619,40.39305745803060,-3.6980673403694100,CentrosAsistenciaDrogodependientes
3,Centro de Atención a las Adicciones (CAD) de H...,CALLE MINAYA 7,HORTALEZA,28043,446072,4479929,40.468288815918500,-3.636150078507100,CentrosAsistenciaDrogodependientes
4,Centro de Atención a las Adicciones (CAD) de L...,CALLE CAMARENA 10,LATINA,28047,435820,4471982,40.39597072367930,-3.7562716852987800,CentrosAsistenciaDrogodependientes

In [40]:
# Guardamos centros_medicos_clean.csv en la carpeta de data
centros_medicos_clean.to_csv('../data/centros_medicos_clean.csv')

## Farmacias en madrid

In [41]:
farmacias = pd.read_csv("../data/oficinas_farmacia.csv", encoding='latin-1', sep=';', error_bad_lines=False)
farmacias.head()

,farmacia_nro_soe,titular_nombre,direccion_vial_tipo,direccion_vial_nombre,direccion_vial_nro,municipio_nombre,localizacion_coordenada_x,localizacion_coordenada_y
0,2,Amaya Corral Palomino,PLAZA,del Dos de Mayo,6,Madrid,440267.0,4475426.0
1,3,Montserrat Gimenez Mestre,CALLE,de Ríos Rosas,50,Madrid,440954.0,4477004.0
2,4,Justo Aquilino Corral Aragon,CALLE,de Argensola,12,Madrid,441063.0,4475193.0
3,5,Irene Arroita Del Campo,CALLE,de Alcalá,98,Madrid,442754.0,4475148.0
4,6,Esther Sansi Ponsico,PLAZA,de Salesas,7,Madrid,441090.0,4475021.0

### Limpieza y análisis general

In [42]:
farmacias.shape

(2901, 8)

In [43]:
farmacias.keys()

Index(['farmacia_nro_soe', 'titular_nombre', 'direccion_vial_tipo',
       'direccion_vial_nombre', 'direccion_vial_nro', 'municipio_nombre',
       'localizacion_coordenada_x', 'localizacion_coordenada_y'],
      dtype='object')

In [44]:
farmacias.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2901 entries, 0 to 2900
Data columns (total 8 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   farmacia_nro_soe           2901 non-null   int64
 1   titular_nombre             2901 non-null   object
 2   direccion_vial_tipo        2897 non-null   object
 3   direccion_vial_nombre      2897 non-null   object
 4   direccion_vial_nro         2886 non-null   object
 5   municipio_nombre           2901 non-null   object
 6   localizacion_coordenada_x  2888 non-null   float64
 7   localizacion_coordenada_y  2888 non-null   float64
dtypes: float64(2), int64(1), object(5)
memory usage: 181.4+ KB

In [45]:
farmacias.isnull().sum()

farmacia_nro_soe              0
titular_nombre                0
direccion_vial_tipo           4
direccion_vial_nombre         4
direccion_vial_nro           15
municipio_nombre              0
localizacion_coordenada_x    13
localizacion_coordenada_y    13
dtype: int64

* En este caso nuestro dataframe no tiene apenas valores nulos en comparación con la cantidad de filas que tenemos. Por ello vamos a elimanar las columnas que tengas valores nulos.
* Lo que haremos en vez de eliminar columnas será concatenar las columnas de: 'direccion_vial_tipo', 'direccion_vial_nombre', 'direccion_vial_nro' porque si nos fijamos es el nombre de la calle partida y dividida en 3 columnas. 
* Al juntar estas tres columnas veremos si los valores NAN de las direcciones coinciden con los valores NAN de las columnas de las coordenadas (que son las que necesitamos)
    - Si estos valores NAN no coincidieraran eliminaremos solamente las filas que contengan valores nulos en las columnas de coordenadas X y coordenadas Y
    
    - Y, si si coinciden, lo que haremos será eliminar esas filas que al final y al cabo no va a afectar al desarrollo de este proyecto porque son una cantidad insignificante de datos de los cuales nos vamos a poder deshacer.

In [46]:
farmacias['direccion'] = farmacias['direccion_vial_tipo'] + ' ' + farmacias['direccion_vial_nombre'] + ' ' + farmacias['direccion_vial_nro']

In [47]:
farmacias = farmacias.drop(['direccion_vial_tipo', 'direccion_vial_nombre', 'direccion_vial_nro', 'farmacia_nro_soe'], axis=1)
farmacias.head()

,titular_nombre,municipio_nombre,localizacion_coordenada_x,localizacion_coordenada_y,direccion
0,Amaya Corral Palomino,Madrid,440267.0,4475426.0,PLAZA del Dos de Mayo 6
1,Montserrat Gimenez Mestre,Madrid,440954.0,4477004.0,CALLE de Ríos Rosas 50
2,Justo Aquilino Corral Aragon,Madrid,441063.0,4475193.0,CALLE de Argensola 12
3,Irene Arroita Del Campo,Madrid,442754.0,4475148.0,CALLE de Alcalá 98
4,Esther Sansi Ponsico,Madrid,441090.0,4475021.0,PLAZA de Salesas 7

In [48]:
farmacias = farmacias.reindex(columns=['titular_nombre','direccion','municipio_nombre','localizacion_coordenada_x','localizacion_coordenada_y'])
farmacias.head()

,titular_nombre,direccion,municipio_nombre,localizacion_coordenada_x,localizacion_coordenada_y
0,Amaya Corral Palomino,PLAZA del Dos de Mayo 6,Madrid,440267.0,4475426.0
1,Montserrat Gimenez Mestre,CALLE de Ríos Rosas 50,Madrid,440954.0,4477004.0
2,Justo Aquilino Corral Aragon,CALLE de Argensola 12,Madrid,441063.0,4475193.0
3,Irene Arroita Del Campo,CALLE de Alcalá 98,Madrid,442754.0,4475148.0
4,Esther Sansi Ponsico,PLAZA de Salesas 7,Madrid,441090.0,4475021.0

In [49]:
farmacias.isnull().sum()

titular_nombre                0
direccion                    17
municipio_nombre              0
localizacion_coordenada_x    13
localizacion_coordenada_y    13
dtype: int64

In [50]:
# Investigamos en que filas tenemos nuestros valores nulos
nan_rows = farmacias[farmacias.isnull().any(1)]
nan_rows

,titular_nombre,direccion,municipio_nombre,localizacion_coordenada_x,localizacion_coordenada_y
365,Juan Gil Rodriguez,AVDA de España 33,Villa del Prado,NaN,NaN
621,Carlos Galdon Cabrera,NaN,Madrid,449762.0,4482623.0
746,Mª Soledad Garcia Lope,CALLE de Gerardo Diego 4,Madrid,NaN,NaN
823,Patricia Garcia Gomez,CALLE del Conde de Peñalver 51,Madrid,NaN,NaN
861,Miriam Batuecas Mohedano,CALLE de Amado Nervo 4,Madrid,NaN,NaN
873,María Aurora Martín Pedraza,NaN,Madrid,439199.0,4474678.0
972,Santiago Javier Sanchez Serrano,NaN,Madrid,442504.0,4471679.0
1152,Carmen Benitez-Donoso Medio,CALLE de María de Maeztu 52,Madrid,NaN,NaN
1216,Silvia Gea Barra,NaN,Madrid,434265.0,4470346.0
1358,Mª Paz Gonzalez Cuesta,NaN,Madrid,434225.0,4485852.0
1581,Almudena Carmen Pastor Lopez,NaN,Madrid,437904.0,4481496.0
1682,Rafael Revuelta De Rojas,NaN,Alcorcón,431857.0,4467243.0
1768,Laura Del Castillo-Olivares Lanero,NaN,Leganés,433675.0,4463991.0
1845,Mª Luisa Alonso Ortega,CALLE Alfonso VI 2,Alcalá de Henares,NaN,NaN
1992,Javier Tamayo Carmona,CALLE del General Marvá 9,Madrid,NaN,NaN
2327,Mª Isabel Lopez Gutierrez,CTRA de Pastrana S/N,Anchuelo,NaN,NaN
2362,Santiago Mariano Lastres Baselga,NaN,Villanueva de la Cañada,394475.0,4486003.0
2390,Alicia Vanaclocha Lopez,NaN,"Escorial, El",410375.0,4495071.0
2402,Gloria Iglesias Serrano,NaN,Venturada,449279.0,4515820.0
2419,Manuel Calatrava Rico,NaN,Madrid,451683.0,4479509.0
2447,Ana Mª Otero Morales,AVDA de Montepríncipe S/N,Boadilla del Monte,NaN,NaN
2463,Alicia Gallego Buzon,NaN,"Rozas de Madrid, Las",425082.0,4486385.0
2504,Mª Dolores Noguera Cases,NaN,Madrid,446500.0,4481073.0
2566,Pedro Guillermo Garijo Reillo,PASEO de los Pinos S/N,Alcalá de Henares,NaN,NaN
2594,Beatriz Castellanos Dengra,NaN,San Sebastián de los Reyes,447936.0,4490204.0
2669,Isabel Fernandez Garcia,AVDA Fuenlabrada 78,Leganés,NaN,NaN
2725,Carlota Ceres Vega-Leal,NaN,Nuevo Baztán,477474.0,4467199.0
2779,Rosario Celia Reyes Parra,AVDA de Juan Carlos I S/N,Getafe,NaN,NaN
2823,Jesus Ramos Martin,NaN,Rivas-Vaciamadrid,454782.0,4469871.0
2842,Marta Garcia Solano,AVDA Europa 15,Pozuelo de Alarcón,NaN,NaN

* Las únicas filas que vamos a eliminar son aquellas que contengan los valores nulos en las coordenadas ya que es en lo que nos vamos a fijar aposteriori. Porque el no tener la dirección exacta de la las farmacias no nos perjudica al derrallo de este proyecto ya que poseemos sus coordenadas
* Esto lo haremos de la siguiente manera:

In [51]:
farmacias_clean = farmacias.dropna(subset=['localizacion_coordenada_x', 'localizacion_coordenada_y'])
farmacias_clean.head()

,titular_nombre,direccion,municipio_nombre,localizacion_coordenada_x,localizacion_coordenada_y
0,Amaya Corral Palomino,PLAZA del Dos de Mayo 6,Madrid,440267.0,4475426.0
1,Montserrat Gimenez Mestre,CALLE de Ríos Rosas 50,Madrid,440954.0,4477004.0
2,Justo Aquilino Corral Aragon,CALLE de Argensola 12,Madrid,441063.0,4475193.0
3,Irene Arroita Del Campo,CALLE de Alcalá 98,Madrid,442754.0,4475148.0
4,Esther Sansi Ponsico,PLAZA de Salesas 7,Madrid,441090.0,4475021.0

In [52]:
farmacias_clean.isnull().sum()

titular_nombre                0
direccion                    17
municipio_nombre              0
localizacion_coordenada_x     0
localizacion_coordenada_y     0
dtype: int64

### Conversion de coordenadas UTM a coordenadas geográficas

In [53]:
import pyproj
_projections = {}

def unproject(z, l, x, y):
    if z not in _projections:
        _projections[z] = pyproj.Proj(proj='utm', zone=z, ellps='WGS84')
    if l < 'N':
        y -= 10000000
    lng, lat = _projections[z](x, y, inverse=True)
    return (lat, lng)

In [54]:
x = list(farmacias_clean.localizacion_coordenada_x)
y = list(farmacias_clean.localizacion_coordenada_y)

In [55]:
lat, lng = unproject(30, "N", x, y)

In [56]:
lat

[40.42732576755214,
 40.44159015864691,
 40.425283566800815,
 40.42499625604595,
 40.423736021015685,
 40.48033217207024,
 40.42715438430698,
 40.440944359704474,
 40.47015953201248,
 40.451125586657554,
 40.431886394491066,
 40.38320286939667,
 40.40665771428301,
 40.41902972127504,
 40.488337431707684,
 40.439390827259636,
 40.47327871249653,
 40.39873789086786,
 40.43160804265021,
 40.43470142379098,
 40.4346698727368,
 40.30766227970144,
 40.38126295212405,
 40.421292068835115,
 40.39219795893028,
 40.381566477892015,
 40.4221913281943,
 40.54479414961183,
 40.39920880060571,
 40.7412893144225,
 40.42524657197511,
 40.3997355980977,
 40.40589276821121,
 40.401401780627076,
 40.44149147298918,
 40.43491305155747,
 40.43266382647799,
 40.29990916420958,
 40.43579427587019,
 40.383038250486095,
 40.414326722014906,
 40.41322086075534,
 40.42552021830656,
 40.409186069278064,
 40.411197355761274,
 40.51128069750115,
 40.411472836839884,
 40.43651654044908,
 40.41120872310375,
 40.42653886505667,
 40.477828711432885,
 40.43554178130944,
 40.40388775788258,
 40.404540988260045,
 40.42780890689514,
 40.410516248999244,
 40.54107916113116,
 40.423347324767434,
 40.672945852947464,
 40.41240676568346,
 40.441597544264674,
 40.518462662918324,
 40.40179709089706,
 40.38228343821056,
 40.40639778517538,
 40.45472171518647,
 40.38163933668241,
 40.424006793757144,
 40.41354735230987,
 40.39836292801433,
 40.40943619737596,
 40.22872809179096,
 40.25623003546413,
 40.24473057833211,
 40.36219682729422,
 40.42988007314315,
 40.44611551124869,
 40.65887716920595,
 40.46073485990614,
 40.49567586810814,
 40.44984567447985,
 40.42610454654765,
 40.2830010312818,
 40.464577264260605,
 40.42466104222096,
 40.41957304586084,
 40.40211350058275,
 40.45942576220755,
 40.436054054885275,
 40.41559783162377,
 40.42981628672901,
 40.03252075648634,
 40.47903619984566,
 40.43401697743382,
 40.417182623460015,
 40.42174299425921,
 40.42440740634838,
 40.81375723470562,
 40.414012657041106,
 40.48607771999854,
 40.38558354034647,
 40.4253262690736,
 40.423133683844256,
 40.42891518025866,
 40.42996250596945,
 40.29985227455796,
 40.42222501585195,
 40.41807120588808,
 40.433998066420756,
 40.50475784754513,
 40.424379546634555,
 40.42521738745048,
 40.26313117018091,
 40.10821481705235,
 40.371003213591344,
 40.382224245568,
 40.3955787884439,
 40.432807182095445,
 40.400232378446034,
 40.45458496253935,
 40.35732840557592,
 40.43106854092805,
 40.42636357163783,
 40.402926078358725,
 40.369264483485864,
 40.42721899181311,
 40.78443950837005,
 40.438666391824086,
 40.38774229997588,
 40.49628245303045,
 40.37774944553244,
 40.422960541902015,
 40.423604030537724,
 40.39625653004267,
 40.447166324052155,
 40.431717597416444,
 40.456761009090684,
 40.437225819189095,
 40.190698350894195,
 40.43474812864404,
 40.38650505137399,
 40.42872460793507,
 40.4310889101898,
 40.591520327543364,
 40.42674661454048,
 40.367391261995444,
 40.40820706933987,
 40.44608871501887,
 40.50305420593452,
 40.41558969878194,
 40.44439382774928,
 40.418453092476696,
 40.388209512059554,
 40.42833197143878,
 40.40179884850325,
 40.435353611322434,
 40.37799658175069,
 40.43133918378745,
 40.41352109039678,
 40.45941492126373,
 40.41851749419159,
 40.43434087801791,
 40.45328911336081,
 40.678967978885964,
 40.42030027586043,
 40.44340967398338,
 40.41740481877519,
 40.43429371280491,
 40.402345372789995,
 40.33783929657605,
 40.659437025973205,
 40.42478977403233,
 40.43599654919191,
 40.41736391994379,
 40.42946684922911,
 40.40733963124862,
 40.46503651477624,
 40.446899367230536,
 40.40073732100622,
 40.43216815980974,
 40.16700935769277,
 40.42992438759644,
 40.46563787303081,
 40.48255639402011,
 40.42826967500562,
 40.47403504404453,
 40.36120548085435,
 40.4326655084609,
 40.42043758552456,
 40.426782457232946,
 40.42797634212305,
 40.41055081620407,
 40.415702594239626,
 40.43334916229943,
 40.361520692031405,
 40.42424511501873,
 40.48563984498608,
 40.429642975386955,
 40.434704042539956,
 40.44744522437497,
 40.43734227083131,
 40.44484506644351,
 40.404783090116,
 40.44686751080717,
 40.40842413346557,
 40.43197323391738,
 40.49392992670533,
 40.37994560667209,
 40.59077895918746,
 40.4216851836253,
 40.3720031328464,
 40.40444432066965,
 40.42959872010539,
 40.99337475189471,
 40.42595852669413,
 40.39392871595583,
 40.43134629455485,
 40.448377395964584,
 40.437011815705176,
 40.391946072897035,
 40.41401619224435,
 40.48227628009126,
 40.23118106791907,
 40.415428262367854,
 40.444560515027895,
 40.443027911864796,
 40.03011491969339,
 40.37070572529301,
 40.43511445885231,
 40.424217672351475,
 40.45644815748382,
 40.45346953869823,
 40.44652823098532,
 40.48391506150578,
 40.92195836614651,
 40.41899376156695,
 40.399069622422225,
 40.437221879299194,
 40.38853422854253,
 40.42582931223353,
 40.43233477011899,
 40.42050269361053,
 40.4631105866557,
 40.40445378028233,
 40.44696621395717,
 40.50670470681565,
 40.44668432696183,
 40.40976020106286,
 40.43663215586243,
 40.30154651740167,
 40.43196223786576,
 40.50549995859198,
 40.41965866477313,
 40.429760679670316,
 40.42563881809133,
 40.463655082329225,
 40.41370441945541,
 40.499672129693316,
 40.42955822304715,
 40.424133147174324,
 40.28987422293589,
 40.44869595926888,
 40.42884568770056,
 40.400440048898666,
 40.413611988739845,
 40.41339381606776,
 40.412140874423244,
 40.73497643900616,
 40.21450925800106,
 40.4351428856583,
 40.432156088650764,
 40.242030627262665,
 40.42908178057699,
 40.41713777946392,
 40.38405698080932,
 40.32932737728772,
 40.43142748407601,
 40.28745731244604,
 40.467651811407634,
 40.38571922100332,
 40.03328094868546,
 40.41170836563297,
 40.42220544162285,
 40.4284314280418,
 40.411719489151345,
 40.37891852469916,
 40.4361077568937,
 40.41362215417064,
 40.396196739603596,
 40.419673161784885,
 40.43639200796278,
 40.41999692894355,
 40.475087690270364,
 40.42905919445904,
 40.481063874081805,
 40.417648699911425,
 40.422782060829526,
 40.43128380458864,
 40.39496538597312,
 40.44795997261225,
 40.42317913388005,
 40.40899842407253,
 40.15905128871327,
 40.404532083303366,
 40.44621645865999,
 40.40846546919829,
 40.42395898009015,
 40.42592617086169,
 40.407536757940726,
 40.49180346586771,
 40.42607325056395,
 40.4390069291927,
 40.41625036477865,
 40.43515373703809,
 40.42661494898478,
 40.43296912267702,
 40.471437258507514,
 40.3277537202569,
 40.42364135551976,
 40.379629455099156,
 40.23215588596862,
 40.416344405162995,
 40.46329357013303,
 40.43518309239303,
 40.42383415964654,
 40.40147077571048,
 40.39135988285641,
 40.463980544642546,
 40.42528520591679,
 40.43147515556276,
 40.412347534050234,
 40.42849323684807,
 40.44543271052986,
 40.434482355020364,
 40.41605396705638,
 40.4050452699879,
 40.451574078442725,
 40.42163951811546,
 40.39326650713988,
 40.419027998813284,
 40.42769371384158,
 40.436022292619185,
 40.59678876247341,
 40.42013229940698,
 40.411358080688004,
 40.432894318812636,
 40.40097163352805,
 40.419505483348225,
 40.405734979252934,
 40.41755029472886,
 40.39270620078449,
 40.415159494178006,
 40.402283460921915,
 40.42646951228011,
 40.3957115618619,
 40.11109802986262,
 40.454296665131814,
 40.42617172254698,
 40.44670143942166,
 40.294283449683476,
 40.32340412287805,
 40.41013885438273,
 40.422945140149636,
 40.34709974906103,
 40.421635752689895,
 40.42214350568379,
 40.43506680129003,
 40.43421097176292,
 40.487519301621056,
 40.45532447797145,
 40.41238415295454,
 40.3927239932323,
 40.413857131694584,
 40.44206085465833,
 40.41550304370941,
 40.423339216834954,
 40.42611046703453,
 40.42564336213793,
 40.43589157948128,
 40.42413015712283,
 40.41741332921931,
 40.42499211349089,
 40.43626559968022,
 40.404153429390156,
 40.42724753582278,
 40.42509795241873,
 40.47020736457552,
 40.43069020142128,
 40.30269047527992,
 40.44864701282808,
 40.41002686047037,
 40.57796800400356,
 40.343449728422414,
 40.40473536295758,
 40.44034636422129,
 40.422106744590224,
 40.44292321572182,
 40.44655900916208,
 40.43016042663645,
 40.62683285611251,
 40.450233842712194,
 40.45153606372748,
 40.90498510143469,
 40.42565022483593,
 40.42150352366404,
 40.104611902718595,
 40.39698815732554,
 40.033121873628964,
 40.42999521972719,
 40.45900928877457,
 40.421877915371375,
 40.42355484279626,
 40.30555615510893,
 40.42017151231193,
 40.42034858857547,
 40.440347861752755,
 40.419693550873454,
 40.45893808219038,
 40.395439912761944,
 40.21042998062734,
 40.40646332617296,
 40.50364682318691,
 40.71405746449387,
 40.40341505084375,
 40.45263699484527,
 40.460068811451194,
 40.48249399568889,
 40.43746439175229,
 40.44733496625741,
 40.427477073793575,
 40.451030264464535,
 40.45564863511601,
 40.39552233296512,
 40.429109464384105,
 40.43610317904186,
 40.45625310249637,
 40.40899223788716,
 40.4349390116368,
 40.404261028367316,
 40.45737208631928,
 40.432397131976465,
 40.39363359123476,
 40.397038007783806,
 40.415935026545895,
 40.40305560187432,
 40.42792340380393,
 40.43230947703682,
 40.45734469141239,
 40.373019167038024,
 40.39703235228301,
 40.40886543113545,
 40.82385499900395,
 40.46627538101803,
 40.39728705406941,
 40.41118902268764,
 40.42356617123522,
 40.47797638457788,
 40.39462066264389,
 40.158935100424074,
 40.38647301440591,
 40.453551432773935,
 40.434816105563215,
 40.39688396820553,
 40.49101619267171,
 40.42851906662392,
 40.437821229898354,
 40.38557486339072,
 40.39870936487291,
 40.42600911714993,
 40.37421741078731,
 40.39280870828864,
 40.41251515281004,
 40.42543635349233,
 40.42352325570247,
 40.42236772349696,
 40.032573286232775,
 40.43189823933156,
 40.430168310022964,
 40.857456961673634,
 40.40639217089337,
 40.36207624195714,
 40.430665796706016,
 40.43188237940391,
 40.661714229643195,
 40.36558261033961,
 40.41738988913394,
 40.431680263518295,
 40.396647031914846,
 40.43507817411744,
 40.42574203948707,
 40.356571964489895,
 40.41136562129956,
 40.43557210144017,
 40.4249974127591,
 40.42791371004809,
 40.582441908099064,
 40.39845684203689,
 40.43113591910882,
 40.42755302964726,
 40.42411622484769,
 40.49416554867838,
 40.39330145657879,
 40.30051955002121,
 40.37412002639439,
 40.43480146011174,
 40.43598425063626,
 40.59140355452012,
 40.428302971723255,
 40.28394420649658,
 40.40513969965411,
 40.351198504902506,
 40.14035823061539,
 40.630450911726676,
 40.42518247305141,
 40.43074743192953,
 40.43779554773945,
 40.39498158380592,
 40.4347692101135,
 40.434623404655696,
 40.41698796256492,
 40.42845380325898,
 40.428948687371694,
 40.46233479120729,
 40.48691295728145,
 40.424707291043845,
 40.3976287616166,
 40.41941413839247,
 40.4293899871763,
 40.361910890711314,
 40.48133437429534,
 40.43731166082116,
 40.42928428193155,
 40.371158604660955,
 40.412597380772176,
 40.44722088614279,
 40.43403370267321,
 40.456893364947085,
 40.44033253425994,
 40.11811063873669,
 40.13341878322889,
 40.501131624541124,
 40.45995059805591,
 40.39547162285543,
 40.393915538654,
 40.395887350368156,
 40.442568801556845,
 40.45809430834131,
 40.45268577635674,
 40.42395285054612,
 40.47669457349691,
 40.41796898641728,
 40.39846257887404,
 40.43851018845948,
 40.41107385544216,
 40.44856378028068,
 40.38959005332046,
 40.432918902854496,
 40.46500857184064,
 40.426376948258714,
 40.385621933263195,
 40.46941192274642,
 40.42386705743845,
 40.431893868615234,
 40.394596849534665,
 40.44356028731111,
 40.508562416725496,
 40.439444037247824,
 40.459037250704654,
 40.44539908191193,
 40.458737152738465,
 40.40351125140852,
 40.410025434772315,
 40.4589823502249,
 40.42391173989409,
 40.44748125620999,
 40.39769358530053,
 40.43461868721705,
 40.379901382025686,
 40.43820711030065,
 40.41609700735167,
 40.38967793324249,
 40.408319544999344,
 40.38745246663351,
 40.418976641617284,
 40.43332506495991,
 40.46703012500681,
 40.39010080140659,
 40.42629584312399,
 40.45206959831513,
 40.430867363547044,
 40.459567791300366,
 40.381564615777705,
 40.46738618278016,
 40.439352514893656,
 40.49351898073947,
 40.18703932098733,
 40.46749516540798,
 40.366332944533745,
 40.38502446742041,
 40.38602248756309,
 40.447889410682464,
 40.40720688436461,
 40.468692457048654,
 40.45347029428627,
 40.40634274628476,
 40.43000604479496,
 40.48371977307501,
 40.42666327782543,
 40.43187173962767,
 40.57677895509865,
 40.43737788642008,
 40.40071896626026,
 40.42025323307942,
 40.44717850209263,
 40.4168033256784,
 40.42929052872776,
 40.41135939059537,
 40.45482134290768,
 40.40218963749833,
 40.396673715282404,
 40.4927882536863,
 40.425559052501725,
 40.47020815755241,
 40.46425286945689,
 40.44002262862538,
 40.39065205319425,
 40.40542736624263,
 40.39163190172913,
 40.44249309508643,
 40.44763025542355,
 40.43966512241372,
 40.46098777736209,
 40.39083631750972,
 40.43421959047686,
 40.46318265963255,
 40.43830935386553,
 40.34579048258755,
 40.411307904260454,
 40.47164655780146,
 40.459605104999184,
 40.407936049598746,
 40.453902062713055,
 40.421186328937914,
 40.44691205815793,
 40.18450386006762,
 40.40791894729327,
 40.4299068153012,
 40.484662571040175,
 40.46319575983514,
 40.430254302205014,
 40.473557894118734,
 40.43045056395042,
 40.47415604333617,
 40.47474670168529,
 40.410168407456126,
 40.458215291826214,
 40.39218976486582,
 40.447463577219054,
 40.42679898308527,
 40.40026201211246,
 40.38678575347799,
 40.423661265302066,
 40.40761595398852,
 40.35794736834107,
 40.466417183958654,
 40.39359103192262,
 40.40060176370918,
 40.47007296096932,
 40.43145627146364,
 40.391533389418605,
 40.40727630972937,
 40.43761471938603,
 40.47156905100179,
 40.440909181109305,
 40.40905157375653,
 40.40567099353391,
 40.37486151477042,
 40.39799267034609,
 40.433832982858995,
 40.406734824824845,
 40.38360107378209,
 40.384188172749376,
 40.49711570104089,
 40.45118439090146,
 40.43819380653983,
 40.45630593689596,
 40.45677888110835,
 40.4173477113206,
 40.38330617309565,
 40.47186975324811,
 40.38812349786425,
 40.44086057388518,
 40.46671123266,
 40.47239444594756,
 40.45660971778274,
 40.44965026501609,
 40.42817173335127,
 40.39430651691289,
 40.45069907977342,
 40.384853397811035,
 40.47337562902399,
 40.4262421035585,
 40.40110515985235,
 40.3547317639875,
 40.386311767383,
 40.4381620413557,
 40.46978965442646,
 40.38575404068828,
 40.47851129990629,
 40.36806727677614,
 40.40609648631925,
 40.45595757739297,
 40.41725512490035,
 40.38354449613781,
 40.40314427510168,
 40.38482787187646,
 40.38668811351874,
 40.46247366722986,
 40.43864283167024,
 40.39278351918713,
 40.36574459186279,
 40.49801429976157,
 40.44108395182478,
 40.458253516297276,
 40.38890171678484,
 40.401394057174954,
 40.479400179970575,
 40.40176324533405,
 40.36917197697975,
 40.34358769034663,
 40.38915979218007,
 40.385931104837816,
 40.39014531684335,
 40.38188327604575,
 40.352850030414444,
 40.43103632333193,
 40.45596377013032,
 40.428545055633954,
 40.43148798040319,
 40.34907680052576,
 40.384266689331234,
 40.379328706051545,
 40.47261137963916,
 40.38356511367701,
 40.389335214879566,
 40.401889579387,
 40.36737024293409,
 40.242069085096816,
 40.457380567413075,
 40.43622489305726,
 40.39822788903757,
 40.370091886764875,
 40.44992718845821,
 40.43897972227407,
 40.382356643097424,
 40.39819199908703,
 40.40441556311567,
 40.38360662191089,
 40.44051133990822,
 40.396480371055745,
 40.39735488948596,
 40.39960202835647,
 40.432224610399885,
 40.44525181503468,
 40.38086229473063,
 40.381987935661925,
 40.40637914402538,
 40.43513985321744,
 40.434763539871156,
 40.47633209244269,
 40.484493624545415,
 40.368380696098505,
 40.37293138814832,
 40.39056507615872,
 40.398330277429814,
 40.49219870212631,
 40.45805174555205,
 40.42662316665469,
 40.34691859461451,
 40.40337708317559,
 40.4705727169133,
 40.41965573272094,
 40.4273821794575,
 40.39234664172024,
 40.38368705292966,
 40.40181763998125,
 40.43094545291272,
 40.42510494849438,
 40.42546452571735,
 40.430365616043424,
 40.36078983538966,
 40.40530843526983,
 40.452562154522035,
 40.43828891568302,
 40.36604364045093,
 40.47802846533424,
 40.395327493515424,
 40.43587041097826,
 40.459182065580656,
 40.38998727436122,
 40.423262655255066,
 40.379923795725766,
 40.40265793920639,
 40.39071548921926,
 40.44690655129276,
 40.482112284064286,
 40.451767003535615,
 40.39372278499724,
 40.471946352045556,
 40.45165867974275,
 40.43368799861816,
 40.44751845092679,
 40.387662526164455,
 40.427391188229045,
 40.438134230951434,
 40.451534871481996,
 40.43342163252552,
 40.45179245983449,
 40.38984520426638,
 40.38507632090399,
 40.43766157176896,
 40.43924269025803,
 40.39570110327832,
 40.41175675215466,
 40.433458642118346,
 40.443131805837446,
 40.395228077493776,
 40.44684058171645,
 40.308178839968186,
 40.40491035621298,
 40.38141632772848,
 40.435975389001364,
 40.39485587564296,
 40.389196246935555,
 40.457718253680426,
 40.343722736935824,
 40.46349660173795,
 40.4344641113619,
 40.39745561378433,
 40.40398444990754,
 40.41230690925359,
 40.38654998948602,
 40.42691187181566,
 40.43291974053363,
 40.40716342740684,
 40.42648662480884,
 40.41543220075802,
 40.48619174622596,
 40.44254447841673,
 40.4449598549269,
 40.394758468303124,
 40.34940307631686,
 40.388215697332456,
 40.03436510495122,
 40.46981319004929,
 40.38565848157587,
 40.438943656928004,
 40.44202607104286,
 40.38712315962944,
 40.417832076101874,
 40.43734470075416,
 40.44247378204213,
 40.40083727573239,
 40.42996964604483,
 40.44357364966333,
 40.73919995192921,
 40.4418946024393,
 40.43270441808379,
 40.37131620736259,
 40.42051008863942,
 40.41518928918549,
 40.43571027741585,
 40.35844866962601,
 40.37005996248269,
 40.412545083301815,
 40.46006987021869,
 40.435695388733116,
 40.35132982879579,
 40.4393525971938,
 40.43277806755168,
 40.39745439357611,
 40.51553232884026,
 40.38357502400224,
 40.310226281965186,
 40.45741150703437,
 40.43785981085238,
 40.45664083228406,
 40.47541787544267,
 40.481593047003784,
 40.44448278299028,
 40.40674458558562,
 40.43512210104694,
 40.40828207058487,
 40.34594326114469,
 40.03291819887199,
 40.384630549938386,
 40.39179604352665,
 40.33331809475467,
 40.55339397403407,
 40.42178382059173,
 40.38968290095412,
 40.354320654986346,
 40.38003433830241,
 40.54742812528759,
 40.37660479311406,
 40.44876128369231,
 40.38722409591141,
 40.38786504209369,
 40.43141464034173,
 40.36913400373269,
 40.38647383531483,
 40.43363023472653,
 40.34849763621379,
 40.48676784479087,
 40.45223116091834,
 40.406804226506345,
 40.38234140367374,
 40.43849270591123,
 40.43828841785141,
 40.437501695220796,
 40.41417548401766,
 40.400305360432384,
 40.4317920108598,
 40.473054751033615,
 40.40286129552934,
 40.377071816870355,
 40.395115033497575,
 40.44126962713996,
 40.42465305223084,
 40.4403574212325,
 40.452576444399185,
 40.432086427224206,
 40.43800612241073,
 40.480675389452124,
 40.43013750287815,
 40.36648072662082,
 40.37164474270759,
 40.41122165764764,
 40.39062020992414,
 40.43670401351473,
 40.34543609468244,
 40.377414922891084,
 40.38531695442939,
 40.46704096763957,
 40.406051310402084,
 40.50998339978011,
 40.38504248300826,
 40.45541943611159,
 40.387374160154025,
 40.392463808831465,
 40.40471101519145,
 40.45607622533241,
 40.37424620357312,
 40.37858876383245,
 40.42888066392755,
 40.37673747084577,
 40.40401769066476,
 40.429162614422424,
 40.454389970742,
 40.39865000647901,
 40.487396728493195,
 40.385655402469894,
 40.49125934877776,
 40.40320108881001,
 40.44138327994832,
 40.47440505176876,
 40.43371772993179,
 40.384329232163886,
 40.39372841809417,
 40.46348857888459,
 40.363227533956675,
 40.46007839475552,
 40.37654129744225,
 40.385955999118615,
 40.41298009017487,
 40.383973489121075,
 40.48592788474828,
 40.434611240577674,
 40.38807367873174,
 40.39595986118889,
 40.3959531235568,
 40.472769695274444,
 40.44509609374174,
 40.34303960672499,
 40.40798658013798,
 40.435219057761266,
 40.462555844004,
 40.407573925372084,
 40.3600633436243,

In [57]:
lng

[-3.7041862522231184,
 -3.6962344605329593,
 -3.6947813490726555,
 -3.6748442024512173,
 -3.694447144944195,
 -3.733550712728476,
 -3.534354949041815,
 -3.6806280563022513,
 -3.7151085866975655,
 -3.677381564076322,
 -3.6782259574250102,
 -3.4098102362354927,
 -3.680329688653387,
 -3.705455289572843,
 -3.649873375365068,
 -3.6994071080137965,
 -3.577826245892963,
 -3.701578671994659,
 -3.711057069288305,
 -3.7031549248138957,
 -3.681342929639257,
 -3.7296081336489064,
 -3.715840569198867,
 -3.716995550320937,
 -3.7262779656482725,
 -3.743410877791436,
 -3.69961793944032,
 -3.6290909627362993,
 -3.6676930530902108,
 -4.05538023695018,
 -3.6813185631843273,
 -3.67162233014084,
 -3.7116231191470304,
 -3.6654757039113415,
 -3.6976601872504142,
 -3.6949747793648333,
 -3.704890370166903,
 -3.752916736641123,
 -3.672405447770911,
 -3.7414949635720216,
 -3.702542042341112,
 -3.6902020257485826,
 -3.6868383401765055,
 -3.723879505944752,
 -3.737773151052415,
 -3.678517669592464,
 -3.7051760061079757,
 -3.6934939075036017,
 -3.7071179372153753,
 -3.7178764706603036,
 -3.7088428301494454,
 -3.686244682919234,
 -3.6748926120238106,
 -3.6969014200428636,
 -3.717913552353356,
 -3.6950301727223693,
 -3.6330003301600184,
 -3.7240312928463513,
 -4.089879932110827,
 -3.69974053138831,
 -3.6752460173839725,
 -3.776923593435968,
 -3.708127174905211,
 -3.6302862731854657,
 -3.698240508248819,
 -3.6209616601346823,
 -3.655397058482459,
 -3.706261730597215,
 -3.728039690149927,
 -3.6239669049904926,
 -3.6933572799441783,
 -3.4373115992194667,
 -3.2378179636963376,
 -3.3180440359475205,
 -3.5955793521110277,
 -3.6715920261030925,
 -3.671388046013762,
 -3.765526134818946,
 -3.6991212554733637,
 -3.6878954610715957,
 -3.7031358557682603,
 -3.6960865421490037,
 -3.79436070560052,
 -3.6953747972556403,
 -3.6979224304056815,
 -3.676345953003596,
 -3.700553119739648,
 -3.627385764510812,
 -3.710313953568724,
 -3.709780543516195,
 -3.7210708340869534,
 -3.6032503678488483,
 -3.6663950651626167,
 -3.707545453924879,
 -3.702536386698369,
 -3.705200725300923,
 -3.695161347564142,
 -3.7660705154170486,
 -3.708243431186521,
 -3.615020621732999,
 -3.74075707723347,
 -3.6784901362269813,
 -3.6729041306136896,
 -3.6779249590243137,
 -3.7178421395178205,
 -3.4361460408755615,
 -3.72197995207053,
 -3.7045612386063413,
 -3.7017799615210776,
 -3.672420925832833,
 -3.675545336896757,
 -3.7027496511822853,
 -4.467635328108282,
 -3.3900150615024747,
 -3.694894979946137,
 -3.660268261096159,
 -3.720128082363128,
 -3.674827964943156,
 -3.7505216253571225,
 -3.703043734545643,
 -3.6856630252710207,
 -3.7050033964935016,
 -3.6979518172638652,
 -3.677581670568344,
 -3.6085628165515247,
 -3.701002166765261,
 -3.6956306124562732,
 -3.7088911811518552,
 -3.7097001074459626,
 -3.612080964123997,
 -3.6207374094531666,
 -3.6990482947925902,
 -3.6772114976143753,
 -3.665660711203682,
 -3.7052187479994356,
 -3.7137462443318707,
 -3.7066753642252537,
 -3.7131442217600252,
 -3.6786368452926737,
 -3.675684467185756,
 -3.640787780852761,
 -3.6735375158019545,
 -3.71634506687579,
 -4.147253597216036,
 -3.727875491718078,
 -3.691771953191835,
 -3.698494915754019,
 -3.6651143849568713,
 -3.698403849712653,
 -3.7022605097185175,
 -3.69741898392376,
 -3.6768298024378985,
 -3.7025297873635377,
 -3.6942232697748842,
 -3.6944691330767596,
 -3.6966181544045456,
 -3.779336509798718,
 -3.718116147339951,
 -3.729347695552093,
 -3.699886003240118,
 -3.6781388353999596,
 -3.6698089504988656,
 -3.7028061549146796,
 -3.9723829591503974,
 -3.700965707526048,
 -3.7007576305939986,
 -3.7074656932081465,
 -3.693093788904453,
 -3.605242787185243,
 -3.3814916165536464,
 -3.768040399269805,
 -3.6839191833767146,
 -3.677878175281379,
 -3.6782097623676377,
 -3.7076392346725733,
 -3.703376853822571,
 -3.63923338895726,
 -3.700227847392756,
 -3.7090588030278067,
 -3.679337016203034,
 -3.2782454511648615,
 -3.7005586874913727,
 -3.700257277795284,
 -3.7208207994692777,
 -3.6059702627134125,
 -3.7220863152745185,
 -4.400465624687772,
 -3.7105023009392633,
 -3.7124011035635154,
 -3.709061110196792,
 -3.705348351471313,
 -3.707158194330118,
 -3.7014719696170113,
 -3.6557927433177486,
 -3.553975700783493,
 -3.68003532478942,
 -3.3657612235144927,
 -3.7023948837680623,
 -3.713023257063592,
 -3.6119914598455676,
 -3.699987197190832,
 -3.7032370372285865,
 -3.6295650882142176,
 -3.7113475764922175,
 -3.6520740170562935,
 -3.7146567471898746,
 -3.8718579793175354,
 -4.20953168843945,
 -4.14661461194667,
 -3.6893926544451974,
 -3.6085874520535746,
 -3.703935954961071,
 -3.678120450198374,
 -3.637045231073211,
 -3.712659757250898,
 -3.7072199325768214,
 -3.7008092333485467,
 -3.6789931269342806,
 -3.6874976319975397,
 -3.7333566134804985,
 -3.6987789253784675,
 -3.6653770462570643,
 -3.352057908778206,
 -3.7095194537237908,
 -3.6738724405227097,
 -3.704279338377704,
 -3.603299493890768,
 -3.620472534120144,
 -3.6746623891140544,
 -3.67395230077221,
 -3.783178951244384,
 -3.472352951492684,
 -3.7020046115797585,
 -3.3641944192392055,
 -3.617012510354729,
 -3.7009992963480682,
 -3.6943821684928833,
 -3.6399249147097845,
 -3.6994933961171803,
 -3.7072946082696427,
 -3.667749428118303,
 -3.695793046199152,
 -3.696574563295892,
 -3.7023804584436406,
 -3.6676111997270606,
 -3.6951015535176484,
 -3.7044825945625064,
 -3.70974278025134,
 -3.715908698653787,
 -3.4407695990570613,
 -3.697278743442383,
 -3.6976856621762617,
 -3.7072064038599666,
 -3.6657551636979817,
 -3.674343718214397,
 -3.6989038336468503,
 -3.708558432765021,
 -4.2384800733585495,
 -3.7191110729151315,
 -3.676085131589515,
 -4.0135485405954565,
 -3.6830293836166317,
 -3.6836065964732265,
 -3.69420770332344,
 -3.7104079290038015,
 -3.706315764582081,
 -3.6607137968986194,
 -3.582914859656821,
 -3.853059625110406,
 -3.619696807423699,
 -3.7171345076904623,
 -3.6988297005280737,
 -3.6663143468658044,
 -3.6768284085532317,
 -3.6419780536686654,
 -3.766145351652317,
 -3.7037574561005813,
 -4.013830071287648,
 -3.678278920618565,
 -3.7061090652665842,
 -3.6026007058195035,
 -3.7079128341971126,
 -3.665173791731922,
 -3.6956625503662806,
 -3.6956907866178437,
 -3.6058459401145413,
 -3.691049106749241,
 -3.7175152388726365,
 -3.668217117042218,
 -3.6988963915543502,
 -3.684154637314623,
 -3.6974970266272913,
 -3.7294826045506477,
 -3.703579509784107,
 -3.6647161732813047,
 -3.702930209468336,
 -3.6806453559095456,
 -3.719777875992967,
 -3.6661546723942293,
 -3.703599691518124,
 -3.6956673783924128,
 -3.701708781948057,
 -3.616897731326646,
 -3.6908792808293436,
 -3.6954567494137214,
 -3.6929819667245574,
 -3.7096562358542933,
 -3.6682990510810085,
 -3.700585778211275,
 -3.607249417853047,
 -3.6937992335320136,
 -3.6943448566488875,
 -3.7062041929797167,
 -3.7116839284969014,
 -3.6722550803227,
 -3.697631047967965,
 -3.693180624626427,
 -3.764338299498713,
 -3.683117744491672,
 -3.6077136308477797,
 -3.989213293678942,
 -3.708503618621724,
 -3.6167943460250322,
 -3.70837119955212,
 -3.687068742148553,
 -3.71867069207254,
 -3.694043755929259,
 -3.7046514744852455,
 -3.7108136534630303,
 -3.657401495383068,
 -3.7079902494136485,
 -3.698858008725462,
 -3.6343662079832826,
 -3.7153671348997905,
 -3.7088541770202186,
 -3.650556507136529,
 -3.7092508720007094,
 -3.6742212657074864,
 -3.6945935600789688,
 -3.6998091288316965,
 -3.6757435406774266,
 -3.641799996792665,
 -3.4989946884682332,
 -3.6777660607190987,
 -3.7351701999806064,
 -3.7157629472997242,
 -3.7545953783998547,
 -3.6908202593117214,
 -3.67637240786437,
 -3.698355791566551,
 -3.665790708462626,
 -3.7033757714537567,
 -3.697773755215297,
 -3.6662532008560875,
 -3.6984836042082514,
 -3.389972858995982,
 -3.707475091328958,
 -3.7013685289121803,
 -3.7119826035414145,
 -3.300674646106117,
 -3.862715437045439,
 -3.7008366919586924,
 -3.606004996225567,
 -3.7071544604212825,
 -3.626857727277849,
 -3.6970948333889497,
 -3.673565427279025,
 -3.7111670182943723,
 -3.6559539481835297,
 -3.6894533083118177,
 -3.732482330985305,
 -3.679765258261413,
 -3.699755555548502,
 -3.697359497945214,
 -3.7002087160603954,
 -3.7049344804468056,
 -3.6768829780751404,
 -3.7170063888590494,
 -3.704476046536146,
 -3.7022785942814807,
 -3.691164259166577,
 -3.6724629028045577,
 -3.6765485650915606,
 -3.6924309981024876,
 -3.6450292352461515,
 -3.6851247238300986,
 -3.642538202245783,
 -3.7167180963970097,
 -4.441016173953871,
 -3.704691769184707,
 -3.7132577440959804,
 -3.9523574645132387,
 -3.675726348691012,
 -3.5600337277993366,
 -3.6993108912256742,
 -3.7031652187268436,
 -3.6482566470457614,
 -3.6848591208734978,
 -3.6775837841925316,
 -4.006317020263537,
 -3.700038393492584,
 -3.5945866186134943,
 -3.8784571166376263,
 -3.7071159046503497,
 -3.707532206004573,
 -3.485160812448755,
 -3.6731151029252174,
 -3.603736211921631,
 -3.673479456578784,
 -3.6818364457253696,
 -3.6872845954689994,
 -3.6840363451733245,
 -3.7321390390468556,
 -3.7014005105433676,
 -3.6792888310890284,
 -3.699063294079162,
 -3.7029632801364163,
 -3.6786276662110877,
 -3.773704907050962,
 -3.5734961879562115,
 -3.6270704981371082,
 -3.706140409032491,
 -4.0728980892057,
 -3.6938729418505254,
 -3.6684574668982948,
 -3.7079012719630393,
 -3.366298680031542,
 -3.710977277674023,
 -3.802318122356687,
 -3.669622963705471,
 -3.7038911581542546,
 -3.704422896731684,
 -3.6969969585437514,
 -3.7056784959263522,
 -3.702273462258131,
 -3.4789770482229962,
 -3.710100066100063,
 -3.7070363532238098,
 -3.680376266427483,
 -3.709866160930264,
 -3.6552765370754803,
 -3.694974385705274,
 -3.6676244739659603,
 -3.7017690538943815,
 -3.6907109857376406,
 -3.6856956848807187,
 -3.702422628321573,
 -3.7025535629861865,
 -3.7458494900683914,
 -3.713815823682414,
 -3.6998688498985355,
 -3.538308752965448,
 -3.6961354342575605,
 -3.4879740585039007,
 -3.6985021750609457,
 -3.7076009705414243,
 -3.675150256050385,
 -3.6618622223702655,
 -3.618411434354224,
 -3.7021582941379645,
 -3.7026319872463804,
 -3.6448539628584746,
 -3.6967871134225727,
 -3.722197507589475,
 -3.702029520428793,
 -3.7144710638674,
 -3.709088281772498,
 -3.695863227508726,
 -3.6803360168056525,
 -3.751410856709889,
 -3.669880347779676,
 -3.6996945092435087,
 -3.6673157586256355,
 -3.6756192873323728,
 -3.6775645255187257,
 -3.6035438453481667,
 -3.700414116842814,
 -3.703414229252282,
 -3.70972986565253,
 -3.6066343316413993,
 -3.749544749880612,
 -3.711919558976878,
 -3.686537590029352,
 -3.768338608417575,
 -3.753423223537465,
 -3.7113670555633633,
 -3.7124961563106305,
 -3.668245135661363,
 -3.706377562231439,
 -3.681323562691776,
 -3.906769557906885,
 -3.7109146761926235,
 -3.699226053602765,
 -3.6761880924495705,
 -3.7140832741711427,
 -4.130580008146037,
 -3.6853495044094817,
 -3.6725240990582906,
 -3.6782295806115646,
 -3.713382971975447,
 -3.7213580378979327,
 -3.7212585413176953,
 -3.4383742607111305,
 -3.6271828582996766,
 -3.7000315879758663,
 -3.698110243141436,
 -4.14812608468855,
 -3.7195928393169932,
 -3.20912857986543,
 -3.667185978291088,
 -3.6862839187038876,
 -3.4216479752910414,
 -4.005673702627649,
 -3.7040460149399816,
 -3.714749874983729,
 -3.6995202730010455,
 -3.6228398540603926,
 -3.6828294863988003,
 -3.6981904890185064,
 -3.704915335480546,
 -3.6751734867593187,
 -3.7010083372473384,
 -3.701213749218153,
 -3.7185311624381927,
 -3.670314585037456,
 -3.668290192859922,
 -3.7074160168211994,
 -3.6517577504914684,
 -4.398007061217167,
 -3.368333491367589,
 -3.679447737200781,
 -3.659278216422335,
 -3.6915159995093987,
 -3.725813641961893,
 -3.706610807084328,
 -3.6478293574591723,
 -3.6551488574001634,
 -3.6774265017533794,
 -3.1616547462690967,
 -3.337021325843696,
 -4.067857565313229,
 -3.6593420230882368,
 -3.711242378015347,
 -3.7224669560704076,
 -3.694726541735981,
 -3.6724493646096255,
 -3.6765669867964346,
 -3.6997925939193026,
 -3.609680185573819,
 -3.6647084717498504,
 -3.673335945609715,
 -3.708316127949971,
 -3.6350203738574693,
 -3.7302641501505445,
 -3.6670963444581948,
 -3.7298199583319125,
 -3.6506246312541144,
 -3.720562397951341,
 -3.5290556707520624,
 -3.7189734734917526,
 -3.692900283778453,
 -3.7010970380030863,
 -3.7230736772653317,
 -3.7273170851887714,
 -3.6800648592120475,
 -3.6734857881387852,
 -3.6737623946314413,
 -3.795852515714543,
 -3.7837817851327116,
 -3.704679246723249,
 -3.662102495001373,
 -3.737889996218001,
 -3.7827837851587125,
 -3.6020528207624642,
 -3.673559634101115,
 -3.7176053514087264,
 -3.718080296127217,
 -3.6209692102619173,
 -3.71762326533332,
 -3.674554903393707,
 -3.667563569489484,
 -3.7355614122498464,
 -3.7443356656096403,
 -3.6689139451413655,
 -3.6472802224201826,
 -3.7039048269379156,
 -3.721648556434194,
 -3.7307824194365167,
 -3.685351409645817,
 -3.690571041084995,
 -3.69695077423065,
 -3.704864040075362,
 -3.6941887991570566,
 -3.7145108566565104,
 -3.687012005140507,
 -3.777663532147345,
 -3.6538717533071865,
 -3.686437398456579,
 -3.732350807370511,
 -3.667174029986869,
 -3.7845418417904098,
 -3.7419133480602533,
 -3.697186646882506,
 -3.68004682666541,
 -3.6326673343431026,
 -3.680859654690678,
 -3.701589627672696,
 -3.688535751116604,
 -3.6429512863395437,
 -4.00549570116095,
 -3.6442771187817424,
 -3.69726266658993,
 -3.675574784777336,
 -3.6972708838025823,
 -3.6708372724243032,
 -3.658181885217981,
 -3.723537427363471,
 -3.6551405251841977,
 -3.713151448315785,
 -3.7724228537290414,
 -3.5928265387775196,
 -3.663214569998016,
 -3.689310594837408,
 -3.7232790248359526,
 -3.7168643635838374,
 -3.725695802621675,
 -3.694824619835195,
 -3.6614676996502062,
 -3.6822944816306866,
 -3.6633725189935604,
 -3.642848662882929,
 -3.697519799919072,
 -3.727912876849036,
 -3.6532191840790365,
 -3.6722302676229703,
 -3.676769494415523,
 -3.7120390167129633,
 -3.6754617481444627,
 -3.5835100114567666,
 -3.6770303324564466,
 -3.6712442091343642,
 -3.6967978826825862,
 -3.6762324450336568,
 -3.5862323193180474,
 -3.1054510767518786,
 -3.73904552966832,
 -3.697505088016216,
 -3.6856002259013017,
 -3.649454081332515,
 -3.655043529529711,
 -3.581438500011129,
 -3.648997487734122,
 -3.872970592706228,
 -3.7249724280497345,
 -3.6590444903719077,
 -3.6728176408796247,
 -3.723273298400708,
 -3.693311608961664,
 -3.601217986352538,
 -3.687818900461631,
 -3.6981204078297067,
 -3.6673689452319462,
 -3.7038629303529245,
 -3.689143426553283,
 -3.7200466485683465,
 -3.6512121503706374,
 -3.6912751127712413,
 -3.695337111590855,
 -3.7078958788449676,
 -3.7114483758770134,
 -3.7166228725409627,
 -3.6518489586219975,
 -3.5863641132337025,
 -3.6727865626277905,
 -3.7309376411307515,
 -3.735544363752157,
 -3.604678751702281,
 -3.6629793427597743,
 -3.7081683919755353,
 -3.732586075482633,
 -3.7077480924231447,
 -3.6712322583197334,
 -3.674409799800785,
 -3.688774173018912,
 -3.6498029660104545,
 -3.6773510309505775,
 -3.694810836765285,
 -3.6670590285036804,
 -3.648980708280149,
 -3.7006405185816287,
 -3.669963526747515,
 -3.6286044977318794,
 -3.7263250902965157,
 -3.7106141676642133,
 -3.666940039148245,
 -3.687697166067543,
 -3.6647727998719413,
 -3.6585009747085437,
 -3.668626950492104,
 -3.639700019671867,
 -3.6527019177618136,
 -3.632971641424437,
 -3.561794854011212,
 -3.6860017831540848,
 -3.7282293957718093,
 -3.6895019772566964,
 -3.5854993048794985,
 -3.700383595174352,
 -3.685289892235955,
 -3.613487241975019,
 -3.7380474334189633,
 -3.676840398407582,
 -3.669050127002181,
 -3.7270332591026327,
 -3.746040477956588,
 -3.7461917928867003,
 -3.651558022524946,
 -3.6976177343265473,
 -3.678282059547131,
 -3.7205224834223554,
 -3.618248091144938,
 -3.6915659083513974,
 -3.714234408627992,
 -3.6847183878008716,
 -3.737494448325145,
 -3.6605380089255064,
 -3.7241966328535367,
 -3.6761558888183368,
 -3.701260207144137,
 -3.709849399957541,
 -3.6493903592955603,
 -3.715607230276764,
 -3.7388511967338847,
 -3.730455411950337,
 -3.700832030072739,
 -3.639265013518371,
 -3.7000035100214603,
 -3.6417524896551448,
 -3.647144712000128,
 -3.690077567164664,
 -3.7820359912348134,
 -3.7051352473998,
 -3.711961280275243,
 -3.7237465370819187,
 -3.656614529698488,
 -3.674578046614824,
 -3.6877435411518995,
 -3.774859946219173,
 -3.6502354607192102,
 -3.6474730960689614,
 -3.7622241497811446,
 -3.7070178075449243,
 -3.595610204337932,
 -3.639729346530578,
 -3.7138022603982552,
 -3.699487286886602,
 -3.65993116390569,
 -3.667421161194289,
 -3.7062575624309826,
 -3.7371764988148293,
 -3.6948830289305743,
 -3.6987241387470946,
 -3.681990259473361,
 -3.6076674961751807,
 -3.671493764542889,
 -3.641428270262911,
 -3.670957683144745,
 -3.6795555668499653,
 -3.649416238594495,
 -3.709027645126527,
 -3.6942824277863178,
 -3.708401569667486,
 -3.6594707899083834,
 -3.7436394278618867,
 -3.703424488452476,
 -3.690868990660807,
 -3.6605618490226526,
 -3.629179249791331,
 -3.7146413327668726,
 -3.7490481224182686,
 -3.685574873367893,
 -3.6667635628310853,
 -3.6547327316228513,
 -3.691744476727092,
 -3.7315705460259276,
 -3.6620859013902223,
 -3.636139946017203,
 -3.6250627240762405,
 -3.640025665811267,
 -3.644858607237242,
 -3.5923753366273687,
 -3.678442292941939,
 -3.7067846865402143,
 -3.6537066159995013,
 -3.7614374613579638,
 -3.698227029769449,
 -3.7141630989077106,
 -3.6701542574077783,
 -3.711465657371015,
 -3.636673410328586,
 -3.6693100434300603,
 -3.708004121641653,
 -3.702880310066505,
 -3.71551648276379,
 -3.676325071983886,
 -3.364503235196911,
 -3.6952899007979694,
 -3.667603513068293,
 -3.6909091142837207,
 -3.6968218817918865,
 -3.6843748186881635,
 -3.6901636192767566,
 -3.667107739824899,
 -3.6827666518549536,
 -3.674362435179548,
 -3.7850087852715193,
 -3.6412683042549543,
 -3.7044769720357555,
 -3.701698461292984,
 -3.7036871580657023,
 -3.6719877978152056,
 -3.711868536696321,
 -3.7178434295405998,
 -3.727690382011816,
 -3.6774282522893342,
 -3.641549238020405,
 -3.7400025891756923,
 -3.6690839848751344,
 -3.736239102133708,
 -3.683317244482589,
 -3.7070183797702763,
 -3.6533894504598248,
 -3.607520573275856,
 -3.7421516046516707,
 -3.698889484460516,
 -3.7142543777583685,
 -3.693806695797527,
 -3.63520631944049,
 -3.767294156534167,
 -3.7428796664787476,
 -3.7204006676249386,
 -3.721846290693264,
 -3.6582294293986024,
 -3.672518291024152,
 -3.667759870580536,
 -3.6109644542102006,
 -3.677318147423079,
 -3.7069249616843045,
 -3.670432780156527,
 -3.5892340912678438,
 -3.664538343639834,
 -3.6972637805685813,
 -3.6426066399690042,
 -3.6020242030881584,
 -3.699569279738302,
 -3.6488147800687964,
 -3.7062765291273565,
 -3.680521052665512,
 -3.7048748573784875,
 -3.670541024265979,
 -3.6372614086068564,
 -3.6686397754771596,
 -3.713313939674834,
 -3.6638827289292193,
 -3.6959837179395554,
 -4.067072299326674,
 -3.7024988081586496,
 -3.6324545342380268,
 -3.7416844999590486,
 -3.716704345390393,
 -3.7132179612400256,
 -3.8143592219128224,
 -3.698687738503145,
 -3.753449525780208,
 -3.7139561469371207,
 -3.674581734734732,
 -3.7144249801402065,
 -3.6944692658493317,
 -3.6455811809537666,
 -3.645211766325255,
 -3.618679454857446,
 -3.6630969573290217,
 -3.7046375909153744,
 -3.7287530954364625,
 -3.697471018288721,
 -3.665752514313608,
 -3.6907876844817693,
 -3.3675697248059397,
 -3.723606688093355,
 -3.6717491380040714,
 -3.6824047619938773,
 -3.6624360505767695,
 -3.669055545369607,
 -3.7091676167041485,
 -3.5978389301702354,
 -3.729106671504065,
 -3.6547885591673333,
 -3.711178011896932,
 -3.327484075392374,
 -3.714690356776332,
 -3.736489698875902,
 -3.691497047829118,
 -3.7134714546273475,
 -3.625147493148354,
 -3.736005657313112,
 -3.674975728015695,
 -3.739208072499654,
 -3.731922080800589,
 -3.6833732406413042,
 -3.5973012113084315,
 -3.670135687760388,
 -3.6804246124160915,
 -3.7127857649390936,
 -3.368009214186468,
 -3.6527685272471864,
 -3.706965772272422,
 -3.727809647775417,
 -3.682360154630963,
 -3.6924745304748523,
 -3.646306284338309,
 -3.7255712957372995,
 -3.703079739105406,
 -3.652358631432746,
 -3.718926070853732,
 -3.6960709641305596,
 -3.7667330254913467,
 -3.7002920502651473,
 -3.642687078178784,
 -3.63688227003763,
 -3.695985920804686,

In [58]:
farmacias_clean['latitud'] = lat

<ipython-input-58-2904bf5916a8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmacias_clean['latitud'] = lat

In [59]:
farmacias_clean['longitud'] = lng

<ipython-input-59-b60a15d02ffa>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  farmacias_clean['longitud'] = lng

In [60]:
farmacias_clean.head()

,titular_nombre,direccion,municipio_nombre,localizacion_coordenada_x,localizacion_coordenada_y,latitud,longitud
0,Amaya Corral Palomino,PLAZA del Dos de Mayo 6,Madrid,440267.0,4475426.0,40.427326,-3.704186
1,Montserrat Gimenez Mestre,CALLE de Ríos Rosas 50,Madrid,440954.0,4477004.0,40.441590,-3.696234
2,Justo Aquilino Corral Aragon,CALLE de Argensola 12,Madrid,441063.0,4475193.0,40.425284,-3.694781
3,Irene Arroita Del Campo,CALLE de Alcalá 98,Madrid,442754.0,4475148.0,40.424996,-3.674844
4,Esther Sansi Ponsico,PLAZA de Salesas 7,Madrid,441090.0,4475021.0,40.423736,-3.694447

* Perfecto, ya tendriamos nuestro dataframe de farmcaias limpio y listo para trabjar con él.
* Lo guardaremos como un csv nuevo en nuestra carpeta de data para poder exportarlo en los siguientes notebooks y trabajar con él. de manera limpia y ordenada
* Lo guadaremos de la siguinete manera:

In [61]:
# Guardamos farmacias_clean.csv en la carpeta de data
farmacias_clean.to_csv('../data/farmacias_clean.csv')